#!/usr/bin/env bash
# Checking for command-line argument
if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign Arguments(path, IP_ADDR, usrname, path_sshkey) to variables

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4


# Disablin the Strict Host Key check
scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# Checks if the transfer was successful
if [ $? -eq 0 ]
then
  echo "FILE TRANSFER WAS SUCCESSFULL"
else
  echo "FILE TRANSFER FAILED"
fi
