#!/usr/bin/env bash
#installing Nginx on web-01

sudo apt-get update
sudo apt-get -y install nginx

#Uncomplicated Firewall(UFW), allowing incoming traffic HTTP
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# Tests Nginx configs for Syntax errors
sudo nginx -t

#Restarting...
sudo service nginx start
