#!/usr/bin/env bash
#Script configures a new Ubuntu machine to Perform redirection(301)

sudo apt-get update
sudo apt-get install -y nginx

echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

#Restarting...
sudo service nginx restart
