#!/usr/bin/env bash

# Set variables
MY_ID=496
CONFIG_FILE=/etc/haproxy/haproxy.cfg
INPUT_LINE="..."

# Check hostname
if ! [[ $(hostname) =~ ^$MY_ID-lb-[0-9]+ ]]; then
  echo "Hostname not configured properly..." >&2
  echo "Please set hostname to pattern: $MY_ID-lb-<server_id>..." >&2
  exit 1
fi

# Install and configure HAProxy
sudo apt update
sudo apt install -y haproxy

# Create and configure HAProxy configuration file
sudo tee "$CONFIG_FILE" >/dev/null <<EOF
$INPUT_LINE
EOF

# Start and enable HAProxy service
sudo systemctl start haproxy
sudo systemctl enable haproxy
