#!/usr/bin/env bash
#script pings an IP address passed as an argument
#IPvar variable

# Check if argument is provided
if [ "$#" -ne 1 ]; then
	    # Display usage message if no argument is provided
	        echo "Usage: $(basename "$0") {IP_ADDRESS}"
		    exit 1
fi

IPvar="$1"

# Validate the format of the IP address using a regex
if ! [[ "$IPvar" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
	    echo "Invalid IP address format: $IPvar"
	        exit 1
fi

# Ping the specified IP address
ping -c 5 "$IPvar"
