#!/usr/bin/env bash
#Creates file myscript.pid in the folder specified, displays toinfinitynbeyond indefinitely
#On receiving a SIGTERM, displays ... On receiving a SIGINT, displays....
#On receiving SIGQUIT or SIGTERM; deletes the file and terminates signal
#executes in one term, sudo killed in another

terminator() {
rm /var/run/myscript.pid
exit
}

echo '$$' >> /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap "terminator" SIGQUIT
done
