#!/usr/bin/env bash
#This script manages_process by:  If 'start' arg is passed -
# 	Starts a proc, Creates a file with its pid as content (var/run/my_proc.pid), Echoes " ... "
# If 'stop' arg is passed -
#	Stops the proc, Deletes the file /var/run/my_process.pid, Echoes "'..."
# If 'restart' arg is passed -
#	Stops the proc, Deletes the file /var/run/my_process.pid,
#	...Starts a proc, Creates the file again with its pid as content Echoes "'..."
# If'no other or some other' arg is passed
#	"Usage: manage_my_process {start|stop|restart}"

if [ "${1}" == "start" ]
	then
		./manage_my_process &
		touch /var/run/my_process.pid
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process started"
elif [ "${1}" == "stop" ]
	then
                kill "$(cat ./manage_my_process)"
                rm /var/run/my_process.pid
                echo "$!" > /var/run/my_process.pid
                echo "manage_my_process stopped"
elif [ "${1}" == "restart" ]
	then
                kill "$(cat ./manage_my_process)" 
                rm /var/run/my_process.pid
                ./manage_my_process &
                touch /var/run/my_process.pid
                echo "$!" > /var/run/my_process.pid
                echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
