#!/usr/bin/env bash
# displays "To infinity and beyond" in while loop with a sleep2
#in btwn iterations until 'TRAP "..." ' SIGTERM 
while "true"
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
