#!/usr/bin/env bash
# displays username userID and homeDir for each line of /etc/passwd.
# uses IFS= read -r line cut -d':' --fields

data="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d':' --fields=1,3,6
done < "$data"
