#!/usr/bin/env bash
# displays numbers 1 to 20 with while/do/case.

INDEX=1
while [ $INDEX -lt 21 ]
do
    case $INDEX in

        4)
	    echo $INDEX
	    echo "bad luck from China"
	    ;;
	
	9)
	    echo $INDEX
	    echo "bad luck from Japan"
	    ;;
	
	17)
	    echo $INDEX
	    echo "bad luck from Italy"
	    ;;

	*)
	    echo $INDEX
	    ;;
    esac

    let INDEX=INDEX+1
done
