#!/usr/bin/env bash
# displays info about the school file
# displays when; empty or not, it exists or not

FILE="school"

if [ -e "$FILE" ]
then
    echo "school file exists"
    if [ ! -s "$FILE" ]
    then
# exists but is empty
        echo "school file is empty"
    else
# exists but is not empty
        echo "school file is not empty"
    fi
    if [ -f "$FILE" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
