#!/usr/bin/env bash
# Displays all active IPv4 addr'ses.
# another use of ifconfig. Here, ip is a new command and ifconfig can be missing in some sys

ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1

#ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | awk '{print $2}'
